# Generated by Django 3.0.3 on 2020-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trucks',
            field=models.ManyToManyField(to='dwmf.Truck'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
