# Generated by Django 3.0.4 on 2020-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='truck_owner',
            field=models.BooleanField(default=False),
        ),
    ]
