# Generated by Django 3.0.3 on 2020-03-24 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 14, 53, 4, 45384)),
        ),
        migrations.CreateModel(
            name='TruckPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwmf.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwmf.Menu')),
            ],
        ),
    ]
