<<<<<<< HEAD:mysite/dwmf/migrations/0002_auto_20200323_1609.py
# Generated by Django 3.0.4 on 2020-03-23 23:09
=======
# Generated by Django 3.0.3 on 2020-03-23 23:10
>>>>>>> c3afb9154f9551b8477b9db0ff57c07554faaf0c:mysite/dwmf/migrations/0002_auto_20200323_1610.py

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
<<<<<<< HEAD:mysite/dwmf/migrations/0002_auto_20200323_1609.py
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 16, 9, 18, 326202)),
=======
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 16, 10, 39, 484739)),
>>>>>>> c3afb9154f9551b8477b9db0ff57c07554faaf0c:mysite/dwmf/migrations/0002_auto_20200323_1610.py
        ),
    ]
