# Generated by Django 3.0.4 on 2020-03-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0002_auto_20200324_1453'),
        ('dwmf', '0002_auto_20200324_1451'),
    ]

    operations = [
    ]
