# Generated by Django 3.0.4 on 2020-03-24 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0002_auto_20200323_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 13, 47, 13, 434067)),
        ),
        migrations.CreateModel(
            name='TruckPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dwmf.Truck')),
            ],
        ),
    ]
