# Generated by Django 3.0.3 on 2020-03-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0002_auto_20200323_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 12, 46, 0, 421537)),
        ),
    ]
