# Generated by Django 3.0.4 on 2020-03-23 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0002_auto_20200323_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 12, 55, 51, 21389)),
        ),
    ]
