# Generated by Django 3.0.4 on 2020-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0003_auto_20200321_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='truck_owner',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
