# Generated by Django 3.0.4 on 2020-03-23 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0003_auto_20200323_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 13, 28, 25, 702314)),
        ),
    ]
