# Generated by Django 3.0.3 on 2020-03-24 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0004_auto_20200324_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 14, 12, 32, 574556)),
        ),
    ]
