# Generated by Django 3.0.4 on 2020-03-23 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0004_auto_20200323_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 13, 28, 54, 524316)),
        ),
    ]
