# Generated by Django 3.0.3 on 2020-03-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0005_auto_20200323_1328'),
        ('dwmf', '0003_auto_20200323_1422'),
    ]

    operations = [
    ]
