# Generated by Django 3.0.3 on 2020-03-23 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0006_merge_20200323_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 45, 18, 1274)),
        ),
    ]
