# Generated by Django 3.0.4 on 2020-03-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0008_auto_20200321_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='truck_owner',
            field=models.BooleanField(default=False),
        ),
    ]
