# Generated by Django 3.0.4 on 2020-03-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0009_auto_20200321_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwmf.Truck')),
            ],
        ),
    ]
