# Generated by Django 3.0.4 on 2020-03-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPhoto',
        ),
    ]
