# Generated by Django 3.0.3 on 2020-03-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0002_auto_20200325_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPhoto',
        ),
    ]
