# Generated by Django 3.0.4 on 2020-03-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwmf', '0002_delete_menuphoto'),
        ('dwmf', '0002_auto_20200325_1349'),
    ]

    operations = [
    ]
